urls.py
from django.conf.urls.defaults import *
from rest_framework import viewsets, routers

from django.contrib.auth.models import User, Group

from recordings.models import Recording
from clips.models import Clip,ClipList,Catalog,CatalogClip

from clips.views import ClipViewSet,CatalogClipViewSet,CatalogViewSet
from games.views import GameViewSet,LevelViewSet
from classifiers.views import ClassifierViewSet
from trainingsets.views import TrainingsetViewSet,TrainingsetClipListViewSet

# ViewSets define the view behavior.
class UserViewSet(viewsets.ModelViewSet):
    model = User
    
class GroupViewSet(viewsets.ModelViewSet):
    model = Group

class RecordingViewSet(viewsets.ModelViewSet):
    model = Recording

# Routers provide an easy way of automatically determining the URL conf
router = routers.SimpleRouter(trailing_slash=False)
router.register(r'users', UserViewSet)
router.register(r'groups', GroupViewSet)
router.register(r'recordings', RecordingViewSet)
router.register(r'clips', ClipViewSet)
router.register(r'catalogClips', CatalogClipViewSet)
router.register(r'catalogs', CatalogViewSet)
router.register(r'games', GameViewSet)
router.register(r'levels', LevelViewSet)
router.register(r'classifiers', ClassifierViewSet)
router.register(r'trainingsets', TrainingsetViewSet)
router.register(r'trainingsetClipLists', TrainingsetClipListViewSet)

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    (r'^$', 'main.views.index'),
    (r'^main/about$', 'main.views.about'),
    (r'^main/tour$', 'main.views.tour'),
    (r'^main/people$', 'main.views.people'),

    # Recordings
    (r'^recordings$', 'recordings.views.index'),
    (r'^recordings/(?P<recordingId>\d+)$', 'recordings.views.show'),
    (r'^recordings/dataview/(?P<recordingId>\d+)$', 'recordings.views.dataview'),
    (r'^recordings/abmiview/(?P<recordingId>\d+)$', 'recordings.views.abmiview'),

    # Trainingsets
    (r'^trainingsets$', 'trainingsets.views.index'),
    (r'^trainingsets/new$', 'trainingsets.views.new'),
    (r'^trainingsets/(?P<trainingsetId>\d+)$', 'trainingsets.views.show'),
    
    # Classifiers
    (r'^classifiers$', 'classifiers.views.index'),
    (r'^classifiers/new$', 'classifiers.views.new'),
    (r'^classifiers/(?P<classifierId>\d+)$', 'classifiers.views.show'),
    (r'^classifiers/train/(?P<classifierId>\d+)$', 'classifiers.views.train'),

    # Predictions
    (r'^predictions$', 'predictions.views.index'),
    (r'^predictions/new$', 'predictions.views.new'),
    (r'^predictions/view$', 'predictions.views.view'),
    (r'^predictions/recording/(?P<recordingId>\d+)$', 'predictions.views.recording'),

    # Data
    (r'^data$', 'data.views.index'),
    (r'^data/new$', 'data.views.new'),
    (r'^data/view$', 'data.views.view'),
    (r'^data/recording/(?P<recordingId>\d+)$', 'data.views.recording'),
    
    # Games
    (r'^games$', 'games.views.index'),
    #(r'^games/(?P<gameId>\d+)$', 'games.views.play'),
    (r'^games/show/(?P<gameId>\d+)$', 'games.views.show'),

    # User survey
    (r'^survey$', 'survey.views.index'),
    (r'^surveyAbout$', 'survey.views.about'),
    (r'^survey/submit$', 'survey.views.submit'),
    
    # # Tools
    # (r'^tools/recordingAnnotator/(?P<recordingId>\d+)$', 'tools.views.recordingAnnotator'),
    # (r'^tools/recordingPitchViewer/(?P<recordingId>\d+)$', 'tools.views.recordingPitchViewer'),
    # (r'^tools/recordingAuditoryImageViewer/(?P<recordingId>\d+)$', 'tools.views.recordingAuditoryImageViewer'),
    # (r'^tools/gameBuilder/(?P<gameId>\d+)$', 'tools.views.gameBuilder'),
    # (r'^tools/gamesViewer/$', 'tools.views.gamesViewer'),
    # (r'^tools/buildTrainingsetFromGames$', 'tools.views.buildTrainingsetFromGames'),
    # (r'^tools/trainingsetBuilder/(?P<trainingsetId>\d+)$', 'tools.views.trainingsetBuilder'),

    # User login
    (r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/login.html'}),
    (r'^accounts/logout/$', 'django.contrib.auth.views.logout', {'template_name': 'accounts/logout.html'}),
    (r'^accounts/preferences/$', 'django.contrib.auth.views.login', {'template_name': 'accounts/preferences.html'}),

    # Visualizations
    (r'^visualizations/spectrogram/(?P<recordingId>\d+)$', 'visualizations.views.spectrogram'),
    (r'^visualizations/waveform/(?P<recordingId>\d+)$', 'visualizations.views.waveform'),
    (r'^visualizations/yin/(?P<recordingId>\d+)$', 'visualizations.views.yin'),
    (r'^visualizations/energy/(?P<recordingId>\d+)$', 'visualizations.views.energy'),

    # Audio
    (r'^audio/(?P<recordingId>\d+)$', 'audio.views.play'),
    
    # Assets
    (r'^www/(?P<path>.*)$', 'django.views.static.serve',
     {'document_root': '/var/www/openmir/openmir/www'}),

    (r'^admin/', include(admin.site.urls)),

    # Celery
#    ('^tasks/', include('djcelery.urls')),

    # Django rest framework
    url(r'^api/v1/', include(router.urls)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),

    # old rest framework
    (r'^oapi/v1/trainingsets/(?P<trainingsetId>\d+)$', 'oapi.views.trainingsetId'),

)

clips/models.py
from django.db import models
from django import forms
from django.contrib import admin
import sys

from recordings.models import Recording

class Catalog(models.Model):
    name = models.CharField(max_length = 200)

    def __unicode__(self):
        return self.name

class CatalogClip(models.Model):
    name = models.CharField(max_length = 200)
    catalog = models.ForeignKey(Catalog)
    recording = models.ForeignKey(Recording)
    startSec = models.FloatField()
    endSec = models.FloatField()

    def __unicode__(self):
        return self.name

class Clip(models.Model):
    recording = models.ForeignKey(Recording)
    catalogClip = models.ForeignKey(CatalogClip)
    comments = models.TextField()
    data = models.TextField()
    startSec = models.FloatField()
    endSec = models.FloatField()

    @property
    def name(self):
        return self.catalogClip.name
            
    def __unicode__(self):
        return self.name

class ClipList(models.Model):
    clips = models.ManyToManyField(Clip)
    
    def __unicode__(self):
        return self.name
    
class ClipAdmin(admin.ModelAdmin):
    pass

admin.site.register(Clip, ClipAdmin)

templates/projects/_hreb.html
<div data-role="page" id="hreb"> 

  <div class="main">
    <h1>Welcome to the orcaMatch user study</h1>
    
    <p class="description">
      In this study, we have a few different games that you can play
      in which you listen to orca calls.  In playing the games, you
      will be using your human intelligence to solve problems that
      are difficult for computers but easy for humans.  With the
      classifications you make in these games, you will be helping
      scientists to better understand orca communication.
    </p>

    <p>
      <a href="#menu">Start</a>
    </p>
  </div>

  <div id="hreb-info">

    <h2>Letter of Information for Implied Consent</h2>

    <h3>Citizen science with serious casual games : Three audio case studies</h3>

    <div class="letterhead">
      <p>Department of Computer Science </p>
      <p>Engineering/ Computer Science Building (ECS) </p>
      <p>        Room 504  </p>
      <p>University of Victoria </p>
      <p>Telephone: (250) 472-5700 </p>
      <p>Fax: (250) 472-5708</p>
    </div>

    <p>You are invited to participate in a study entitled "Citizen
      science with serious casual games : Three audio case studies"
      that is being conducted by Steven Ness and George
      Tzanetakis.</p>

    <p>Steven Ness is a Ph.D. student in the department of Computer
      Science at the University of Victoria and you may contact him
      if you have further questions by emailing sness@uvic.ca</p>

    <p>George Tzanetakis is a Faculty member in the department of
      Computer Science at the University of Victoria and you may
      contact him if you have further questions by emailing
      gtzan@cs.uvic.ca.</p>

    <p>As a graduate student, I am required to conduct research as
      part of the requirements for a Ph.D. in Computer Science. It
      is being conducted under the supervision of George
      Tzanetakis. You may contact my supervisor at 250-472-5710.</p>

    <h4>Purpose and Objectives</h4>


    <p>The purpose of this research project is to design mobile and
      web based interfaces and casual games to engage citizen
      scientists to listen to, see, and interact with the
      vocalizations of orcas (killer whales), birdsong and partially
      annotated chants.  We will attempt to design these casual
      mini-games so that they are engaging and fun for our
      participants.  The data collected from these games will be
      used to help train machine learning and machine hearing
      systems to help us to classify these vocalizations. </p>

    <h4>Importance of this Research</h4>

    <p>Research of this type is important because we want to
      investigate ways to make interfaces for citizen scientists
      more engaging and interesting.  By doing this, we hope to
      increase the amount of time and data that citizen scientists
      provide to such projects.  Another main contribution is to use
      these annotations to help researchers and scientists to study
      difficult problems in bioacoustics, primarily scientists
      studying orcas and birdsong.</p>

    <h4>Participants Selection</h4>

    <p>You are being asked to participate in this study because you
      are interested in listening to the sounds of birds, whales
      and/or partially annotated chants, and have some basic
      knowledge of computers.</p>

    <h4>What is involved</h4>

    <p>If you agree to voluntarily participate in this research,
      your participation will include answering a pre-test survey,
      interacting with our web-based or tablet based game and
      answering a post-test survey.</p>

    <h4>Inconvenience</h4>

    <p>Participation in this study may cause some inconvenience to
      you, including taking approximately 30 minutes of your time to
      complete the survey.</p>

    <h4>Risks</h4>

    <p>There are no known or anticipated risks to you by
      participating in this research.</p>

    <h4>Benefits</h4>

    <p>The potential benefits of your participation in this research
      is that you will potentially learn some of the vocalizations
      of orcas, birds and partially annotated chants.  This will
      hopefully be interesting and rewarding for them in itself.
      They will also get to play a game that is designed to be
      entertaining.  The data collected from the participants will
      be used to help us to train machine learning and machine
      hearing classifier systems with the eventual goal of
      automatically segmenting and classifying these
      vocalizations.</p>

    <h4>Voluntary Participation</h4>

    <p>Your participation in this research must be completely
      voluntary. If you do decide to participate, you may withdraw
      at any time without any consequences or any explanation. If
      you do withdraw from the study your data will not be used.</p>

    <h4>Researcher's Relationship with Participants</h4>

    <p>
      The researcher may have a relationship to potential
      participants as a teacher or fellow student. To help prevent
      this relationship from influencing your decision to
      participate, the following steps to prevent coercion have been
      taken:
    </p>

    <p>i) In order to minimize inducement, coercion or potential
      harm, we will emphasize to the participants that we wish for
      them to find this an enjoyable experience, and that their
      responses will in no way be used against them outside this
      study.</p>

    <p>ii) At the start of the study, we will make sure to let the
      students know that their responses will be held in confidence,
      and that individual responses will be anonomized prior to
      publication.  We will ensure that the students know that it is
      important to us that they are protected from any judgment by
      the researchers outside the parameters of this study.  </p>

    <h4>Anonymity</h4>

    <p>In terms of protecting your anonymity we will not ask for
      your name, this survey is anonymous.</p>

    <h4>Confidentiality</h4>

    <p>Your confidentiality and the confidentiality of the data will
      be protected by being anonymous.</p>

    <h4>Dissemination of Results</h4>

    <p>It is anticipated that the results of this study will be
      shared with others in the following ways, in published
      articles, in a thesis, on a website, and in presentations at
      scholarly meetings.</p>

    <h4>Disposal of Data</h4>

    <p>Data from this study will be disposed of by securely deleting
      it from the servers.
    </p>


    <h4>Contacts</h4>

    <p>Individuals that may be contacted regarding this study
      include Steven Ness (sness@uvic.ca) and George Tzanetakis
      (gtzan@cs.uvic.ca)</p>
    
    <p>In addition, you may verify the ethical approval of this
      study, or raise any concerns you might have, by contacting the
      Human Research Ethics Office at the University of Victoria
      (250-472-4545 or ethics@uvic.ca).</p>

    <p>By completing and submitting the questionnaire, YOUR FREE AND
      INFORMED CONSENT IS IMPLIED and indicates that you understand
      the above conditions of participation in this study and that
      you have had the opportunity to have your questions answered
      by the researchers.</p>

    <p>Please print and retain a copy of this letter for your
      reference.</p>
  </div>
</div>

templates/projects/_menu.html
<div data-role="page" id="menu"> 
  
  <div data-role="header" data-position="inline">
	<h1>Orcagame Main Menu</h1>
    {% if user.is_authenticated %}
    <a href="/accounts/profile" rel="external" data-role="button" data-icon="gear" class="ui-btn-right">{{ user.username }}</a>
    {% else %}
    <a href="/accounts/login" rel="external" data-role="button" class="ui-btn-right">Login</a>
    {% endif %}
  </div>

  <div class="menu">
    <h1>
      Welcome to the orcagame!
    </h1>
    <p>
      In this study, we have a few different games that you can play
      in which you listen to orca calls.  In playing the games, you
      will be using your human intelligence to solve problems that
      are difficult for computers but easy for humans.  With the
      classifications you make in these games, you will be helping
      scientists to better understand orca communication.
    </p>
    <ul>
      <li><a href="#orcamatchobv_about" data-rel="external" rel="external">Orca/Background/Voice matching game</a></li>
      <li><a href="#orcamatch_about">Call matching game</a></li>
      <li><a href="/survey" rel="external">User survey</a></li>
    </ul>
  </div>
</div>

templates/projects/_orcamatch_about.html
<div data-role="page" id="orcamatch_about"> 
  
  <div data-role="header" data-position="inline">
    <a href="/main/menu" rel="external" data-icon="home">Home</a>
	<h1>Openmir Matching Game</h1> 
    <a href="/orcamatch" rel="external" data-icon="forward">Play Game</a>
  </div>
  
  <div class="about">
    <div class="play">
      <a href="/orcamatch" rel="external">Play game</a>
    </div>
    <div class="info">
      <p>
        In this game you will be asked to label an unknown clip of
        audio from the Openmir with a call from the Orcalab call
        catalog.  The picture at the top is a button with a
        spectrogram image of the clip to match.  Click it to play
        the sound.  The buttons at the bottom are sounds from the
        Orcalab call catalog, you can click them to hear the sounds
        associated with them.  The clips at the top of the screen
        have either been labelled by a scientist, or by a machine
        learning program that guessed which call it thought matched
        it best.
      </p>
      <p>
        The aim of the game is to find the best matching sound for
        the clip at the top of the screen.  When you've found a
        sound that, according to you, best matches it, click on the
        "Guess" button at the bottom of the screen.  If you've
        labelled it the same as the scientist, you'll score a point.
        If not, don't be too concerned, it's possible that the
        scientist or the machine learning system just classified it
        incorrectly, and your guess will help the Openmir to learn
        and become better.
      </p>
      <p>
        The classifications that you make are very valuable to our
        research, this is a task that is very hard for computers to
        do on their own, but with your labels, we can train the
        computer to eventually automatically find the orca calls in
        the vast archive of sound files we have in the Openmir.
      </p>
      <img src="/assets/images/about/orcamatch.png">
    </div>
  </div>
</div>

templates/projects/_orcamatchobv_about.html
<div data-role="page" id="orcamatchobv_about"> 

  <div data-role="header" data-position="inline">
    <a href="#menu" data-icon="home">Home</a>
	<h1>Openmir Orca/Background/Voice Matching Game</h1> 
    <a href="/orcamatchobv" rel="external" data-icon="forward">Play Game</a>
  </div>

  <div class="about">
    <div class="play">
      <a href="/orcamatchobv" rel="external">Play game</a>
    </div>
    <div class="info">
      <p>
        In this game you are asked to label an unknown clip of audio
        from the Openmir with one of the following labels: Background
        or boat noise, Orca, Distant Orca, Voice note, Unknown call or
        Skip.  This is shown below.  When you label a call, it will
        flash briefly, and then you will be shown the next call.  You
        can also navigate backwards and forwards though the interface
        with the arrows at the top right corner.
      </p>
      <p>
        The classifications that you make are very valuable to our
        research, this is a task that is very hard for computers to
        do on their own, but with your labels, we can train the
        computer to eventually automatically find the orca calls in
        the vast archive of sound files we have in the Openmir.
      </p>
      <img src="/assets/images/about/orcamatchobv.png">
    </div>
  </div>
</div>

templates/projects/about.html
<!DOCTYPE html>
<html lang="en"> 
  {% include "layouts/_xhtml_header.html" %}

  <body class="home"> 

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Orca Talk</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li><a href="/">Home</a></li>
              <li><a href="orcagame">Orca Talk</a></li>
              <li><a href="orcamatchobvAbout">Orca/Background</a></li>
              <li><a href="orcamatchAbout">Orca Match</a></li>
              <li class="active"><a href="about">About</a></li>
              <li><a href="contact">Contact</a></li>
            </ul>

          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

	<div id="body"> 
	  
      <div class="container">

        <div class="hero-unit">
          <h1>About</h1>
          <div class="mainOrcaImageRight">
            <img src="assets/images/orca-flipping.jpg">
          </div>
          <p>
            
	        <h3>Orcas</h3>
	        
	      <p>
	        The fish eating killer whales or orcas, Orcinus Orca, that are the
	        focus of this project live in the coastal waters of the northeastern
	        Pacific Ocean.  They live in the most stable groups documented among
	        mammals, and communicate using a variety of vocalizations including
	        echolocation clicks, tonal whistles, and pulsed calls (Ford et al.,
	        2000).
	      </p>
	      
	      <h3>Our Local Orca Community</h3>
	      
	      <p>
	        The Northern Resident Community consists of more than 200 individually known
	        orcas in three acoustic clans. It is regularly found in the study area of
	        the Johnstone Strait and the adjacent waters off Vancouver Island, British
	        Columbia, from July to October.
	      </p>
	      
          <h3>Recording the Orca Songs</h3>

          <p>
            The goal of the Openmir project is to digitize acoustic data that have
            been collected over a period of 36 years. The acoustic data have been
            recorded using a variety of analog media at the research station
            <a href="http://www.orcalab.org">OrcaLab</a>, located on Hanson
            Island which is located centrally in the study area.</p>
          
          <h3>People</h3>

          <h4>Paul Spong and Helena Symonds</h4>

          <div class="mainOrcaImageRight">
            <img src="assets/images/people/paul_and_helena.jpg">
          </div>

          
	      <p>
		    Dr. Paul Spong and Helena Symonds are the directors of
		    OrcaLab, a land based whale research station on Hanson
		    Island in British
		    Columbia <a href="http://www.orcalab.org">OrcaLab</a>.
		    Their work focuses on the long-term life history of the
		    'northern resident community' of British Columbia orcas
		    and on the protection of orca habitat.  They are also
		    involved in the development of technology that connects
		    people to the natural world via the Internet
		    (www.orca-live.net).  Orca acoustics are a core aspect of
		    OrcaLab's research.
	      </p>

          <div class="mainOrcaImageLeft">
            <img src="assets/images/people/sness.jpg">
          </div>

          <h4>Steven Ness</h4>

          <p>
            Steven Ness is a scientist and computer programmer. He
            received his B.Sc. in Biochemistry at the University of
            Alberta, and is now pursuing his Ph.D. in Computer Science
            with Dr. George Tzanetakis at the University of Victoria
            in Canada. His research focuses on Music, Machine
            Learning, User-Interface design and Bio-acoustics.  Steven
            wrote all the code that makes up this website, so if you
            encounter any problems, please let me know.
          </p>

          <h3>Accessing and Retrieving the Recordings</h3>

          <p>
            Currently we have approximately 20000 hours of analog recordings mostly in
            high quality audio cassettes. In addition to the digitization effort which
            is underway we are developing algorithms and software tools to facilitate
            access and retrieval to this large audio collection.
          </p>


          <p>
            The size of this collection makes access and retrieval especially
            challenging (for example it would take approximately 2.2 years of continuous
            listening to cover the entire archive). Therefore the developed algorithms
            and tools are essential for effective long term studies employing acoustic
            techniques.
          </p>

          <h3>Providing Us with Feedback</h3>
          <p>
            This project is just beginning but we believe it provides many opportunities
            and challenges related to large scale semantic access in a non-typical
            application scenario. We invite other researchers in information access and
            retrieval to provide feedback to us regarding this project.  Please email us
            at <a href="mailto:sness@sness.net">sness@sness.net</a>.
          </p>

          <h3>Looking Forward</h3>
          <p>
            Finally, we hope that in the future researchers from around the world will
            be able to access this repository and use the tools to improve understanding
            of acoustic communication of orcas. The people involved in the project are
            all volunteers and the software developed is open source.
          </p>

          <p>
            We welcome help and contributions from any interested parties.
          </p>

          </p>
        </div>


	    {% include "layouts/_footer.html" %}
	  </div> 

  </body> 
</html>

templates/projects/bootstrap_template.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>orcaTalk</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <script src="js/vendor/jquery.js"></script>
    <script src="js/vendor/bootstrap-transition.js"></script>
    <script src="js/vendor/bootstrap-alert.js"></script>
    <script src="js/vendor/bootstrap-modal.js"></script>
    <script src="js/vendor/bootstrap-dropdown.js"></script>
    <script src="js/vendor/bootstrap-scrollspy.js"></script>
    <script src="js/vendor/bootstrap-tab.js"></script>
    <script src="js/vendor/bootstrap-tooltip.js"></script>
    <script src="js/vendor/bootstrap-popover.js"></script>
    <script src="js/vendor/bootstrap-button.js"></script>
    <script src="js/vendor/bootstrap-collapse.js"></script>
    <script src="js/vendor/bootstrap-carousel.js"></script>
    <script src="js/vendor/bootstrap-typeahead.js"></script>

    <link href="css/vendor/bootstrap.css" rel="stylesheet">
    <link href="css/vendor/bootstrap-responsive.css" rel="stylesheet">
	<link rel="stylesheet" href="css/code/orcatalkMain.css" type="text/css" />

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Orca Talk</a>
          <div class="nav-collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>

            <!-- <p class="navbar-text pull-right"> -->
            <!--   Logged in as <a href="http://twitter.github.com/bootstrap/examples/fluid.html#">username</a> -->
            <!-- </p> -->

          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

    <div class="container">

      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Orca Talk</h1>
        <div class="mainOrcaImageRight">
          <img src="assets/images/orcaMain.jpg">
        </div>
        <p>
          The Northern Resident Orcas are a small population of killer
          whales living off the west coast of British Columbia.  They
          communicate via sight and touch, but primarily through
          sound.  They make three main kinds of vocalizations,
          whistles, echolocation clicks and stereotyped pulsed calls.
          The calls that they make have been classified into different
          call types by scientists, and in this website, we have games
          to help you to learn these calls.  We have a number of games
          for you to play, the first is Orca Talk, which teaches you
          the different calls.  After you learn some orca calls, we
          invite you to play the three games shown below.
        </p>
        <p><a href="orcatalk" class="btn btn-primary btn-large">Play Orca Talk &raquo;</a>
          
        </p>
      </div>

      <!-- Example row of columns -->
      <div class="row">

        <div class="span4">
          <h2>Orca/Background</h2>
          <p>
            In <a href="http://openmir.cs.uvic.ca">The Openmir</a> we
            have over 20,000 hours of orca vocalizations that we have
            digitized.  Scientists have made over 10,000 annotations
            in this archive, but the vast majority of it remains
            unannotated.  In this game, you will be shown a brief clip
            of audio and will be asked to tell us if it has an orca
            call in it, or if it is background noise.
          </p>
          <p>
            <a href="orcamatchobv" class="btn">Play Orca/Background &raquo;</a>
          </p>
        </div>

        <div class="span4">
          <h2>Orca Match</h2>

          <p>
            Once we have found clips of audio that contain orca
            vocalizations, we next want to figure out which orca call
            is in that clip.  We use
            sophisticated <a href="http://en.wikipedia.org/wiki/Machine_learning">Machine
            Learning</a> algorithms to do this, but to make these
            work, we need to train them and verify their results.  In
            this game, you will listen to clips of orca song and will
            see if your classification matches those of our Machine
            Learning robots.  The results of this game will be used to
            help train and test our Machine Learning systems.
          </p>
          <p>
            <a href="orcamatch" class="btn">Play Orca Match &raquo;</a>
          </p>
        </div>

        <div class="span4">
          <h2>User Survey</h2>
          <p>
            We want to make our games better and to do this, we need
            your feedback.  After playing the games, we would love it
            if you would answer a short user survey and tell us about
            your experiences with our game.
          </p>
          <p>
            <a href="survey" class="btn">User Survey &raquo;</a>
          </p>
        </div>
        
      </div>
        <hr>

      <footer>
        <p>© Orcatastic 2012</p>
      </footer>

    </div> <!-- /container -->


</body></html>

templates/projects/show.html
<!DOCTYPE html>
<html lang="en"> 
  {% include "layouts/_xhtml_header.html" %}

  <body class="home"> 

    {% include "layouts/_navbar.html" %}

	<div id="body"> 
	  
      <div class="container">

        <div class="hero-unit">

          <h1>Project : {{ project.name }}</h1>
          
          <table class="data">
            <tr>
              <th>recording name</th>
              <th># clips</th>
            </tr>
            {% for recording in recordings %}
            <tr>
              <td><a href="/recordings/show/{{ recording.id }}">{{ recording.name }}</a></td>
               <td>{{ recording.clip_set.count }}</td>
            </tr>
            {% endfor %}
          </table>           
        </div>
        
      </div>

	  {% include "layouts/_footer.html" %}
	</div> 

  </body> 
</html>